{
  "version": "3",
  "services": {
    "db": {
      "image": "postgres",
      "environment": {
        "POSTGRES_USER": "${DATABASE_USER}",
        "POSTGRES_PASSWORD": "${DATABASE_PASSWORD}",
        "POSTGRES_DB": "${DATABASE_NAME}"
      },
      "healthcheck": {
        "test": [
          "CMD-SHELL",
          "pg_isready"
        ],
        "interval": "10s",
        "timeout": "5s",
        "retries": 5
      }
    },
    "backend": {
      "build": "./backend",
      "environment": {
        "DATABASE_URL": "${DATABASE_URL}",
        "SECRET_KEY": "${SECRET_KEY}"
      },
      "ports": [
        "8000:8000"
      ],
      "depends_on": [
        "db"
      ],
      "healthcheck": {
        "test": [
          "CMD-SHELL",
          "curl --fail http://localhost:8000/healthcheck || exit 1"
        ],
        "interval": "10s",
        "timeout": "5s",
        "retries": 5
      }
    },
    "frontend": {
      "build": "./frontend",
      "ports": [
        "80:3000"
      ],
      "depends_on": [
        "backend"
      ],
      "healthcheck": {
        "test": [
          "CMD-SHELL",
          "curl --fail http://localhost:3000/healthcheck || exit 1"
        ],
        "interval": "10s",
        "timeout": "5s",
        "retries": 5
      }
    }
  }
}