# modules/test_case_generator/engine/test_types.py

TEST_TYPES_REGISTRY = {
    "Smoke Tests": "Smoke: Verify critical core functions and basic reachability (e.g. system starts up, main endpoints respond successfully).",
    "Sanity Tests": "Sanity: Perform quick focused testing on new changes/fixes to verify correctness without executing full regressions.",
    "Regression Tests": "Regression: Verify that recent changes have not broken existing, unchanged components and integration pathways.",
    "Functional Tests": "Functional: Validate system behavior against specified user actions, business rules, inputs, and outputs.",
    "API Tests": "API: Validate request/response payloads, HTTP status codes, headers, response format (JSON/XML), and authentication/authorization scopes.",
    "UI Tests": "UI: Validate page elements, user inputs, visibility, dynamic updates, responsive behavior, CSS rules, and user interaction states.",
    "Database Tests": "Database: Verify CRUD operations, database constraints, schema migrations, transaction integrity, indexing efficiency, and data syncs.",
    "Performance Tests": "Performance: Measure responsiveness, throughput, and resource utilization under standard operating conditions.",
    "Load Tests": "Load: Assess system stability and response times under expected peak traffic and concurrent user load.",
    "Stress Tests": "Stress: Push the system beyond normal operational limits to identify failure thresholds, bottlenecks, and recovery behaviors.",
    "Spike Tests": "Spike: Evaluate response to sudden, massive surges in traffic or requests, verifying stability during high-rate escalations.",
    "Volume Tests": "Volume: Verify performance and behavior when the system handles exceptionally large datasets (e.g. high-volume DB records).",
    "Scalability Tests": "Scalability: Verify the system's ability to scale up or down (CPU, memory, threads) to meet changing demand workloads.",
    "Security Tests": "Security: Assess susceptibility to common vulnerabilities, inputs verification, data leaks, SQL injections, XSS, CSRF, and secure headers.",
    "Penetration Tests": "Penetration: Simulate attacker scenarios (exploit inputs, attempt privilege escalation, bypass checks) to probe for security holes.",
    "Authentication Tests": "Authentication: Validate user identification processes, login/logout, tokens verification, session lifetimes, credentials checks, and rate-limiting.",
    "Authorization Tests": "Authorization: Validate RBAC (Role-Based Access Control) rules, verifying standard users cannot access admin resources, and data separation.",
    "Compatibility Tests": "Compatibility: Ensure the app runs correctly across different environments, hardware configs, operating systems, and versions.",
    "Cross-Browser Tests": "Cross-Browser: Validate that the application's layout, styles, scripts, and behaviors function identically across all target browsers.",
    "Mobile Tests": "Mobile: Validate touch interactions, layouts on mobile viewport sizes, orientation switches, mobile network constraints, and mobile APIs.",
    "Accessibility Tests": "Accessibility: Validate adherence to WCAG 2.1 (A, AA, AAA) requirements, including ARIA tags, contrast ratio, and keyboard navigation.",
    "Localization Tests": "Localization: Verify translation of texts, number/date formatting, currency units, and cultural adaptations for a specific region.",
    "Internationalization Tests": "Internationalization: Verify the design is capable of supporting multiple locales/languages without requiring code changes.",
    "Installation Tests": "Installation: Validate installation steps, dependencies checks, directory configurations, migration scripts, and uninstall cleanliness.",
    "Recovery Tests": "Recovery: Verify system ability to recover from crashes, hardware failures, memory exceptions, or network loss without corrupting data.",
    "Failover Tests": "Failover: Verify that the system transparently switches to a backup or redundant node when a primary component fails.",
    "Reliability Tests": "Reliability: Measure system uptime, failure-free operation under constant load over extended durations, and leak preventions.",
    "Usability Tests": "Usability: Assess user-friendliness, ease of navigation, clarity of instructions, error messaging, layout logic, and aesthetic comfort.",
    "Acceptance Tests (UAT)": "Acceptance (UAT): Validate end-to-end user journeys, satisfaction of business objectives, and correctness of user flows.",
    "Exploratory Tests": "Exploratory: Outline unstructured test scenarios targeting potential weak spots, logical fallacies, and complex workflow paths.",
    "Boundary Value Tests": "Boundary Value: Test values at, just below, and just above defined range boundaries (e.g. 0, min, max, overflow values).",
    "Equivalence Partition Tests": "Equivalence Partition: Partition inputs into groups and test typical representative values from each partition class.",
    "Negative Tests": "Negative: Inject invalid inputs, malformed structures, unexpected types, and out-of-order calls to verify robustness and error handling.",
    "Positive Tests": "Positive: Inject expected valid inputs, following standard paths to verify the success workflows and expected values.",
    "Edge Case Tests": "Edge Case: Test unusual/extreme operational parameters, concurrency states, race conditions, or rare permutations of actions.",
    "Mutation Tests": "Mutation: Design test assertions to detect code changes/mutations (verifying test suite sensitivity to logic changes).",
    "Contract Tests": "Contract: Verify communication between systems (consumers/providers) meets defined API specifications and data contracts.",
    "Chaos Engineering Tests": "Chaos Engineering: Inject faults asynchronously (e.g., kill service instances, slow down DB, drop packets) to verify system resilience."
}
