from tools.json_parser import parse_llm_json
"""
agents/repository_agent.py
───────────────────────────
Repository Agent — Final stage of the pipeline (non-blocking).

Responsibilities:
  - Create a GitHub repository for the generated project.
  - Push all generated code, docs, and infra files as structured commits.
  - Return the repository URL (or None if GitHub is not configured).
  - This agent is non-blocking: pipeline continues even without a GitHub token.
"""

import logging
from state.pipeline_state import PipelineState
from tools.github_tool import create_repo_and_push
from tools.file_writer import get_project_dir

logger = logging.getLogger(__name__)


def repository_agent_node(state: PipelineState) -> dict:
    """
    LangGraph node function for the Repository Agent.

    Reads: `project_plan`, `structured_spec`, `docs`.
    Returns: `repo_url` (string or None).
    """
    logger.info("[RepositoryAgent] Starting repository creation...")
    plan = state.get("project_plan") or {}
    spec = state.get("structured_spec") or {}

    app_name = plan.get("app_name", spec.get("app_name", "generated_app"))
    description = spec.get("description", f"Generated by Cytron.AI — {app_name}")
    project_dir = get_project_dir(app_name)

    repo_url = create_repo_and_push(
        app_name=app_name,
        project_dir=project_dir,
        description=description,
    )

    if repo_url:
        logger.info(f"[RepositoryAgent] ✅ Repository created: {repo_url}")
    else:
        logger.info(
            "[RepositoryAgent] Repository creation skipped (GitHub not configured). "
            "Add GITHUB_TOKEN to .env to enable."
        )

    return {
        "repo_url": repo_url,
        "stage": "repository_agent_complete",
        "agent_logs": {
            **state.get("agent_logs", {}),
            "repository_agent": {
                "repo_url": repo_url,
                "skipped": repo_url is None,
            },
        },
    }
