"""
tools/github_tool.py
─────────────────────
GitHub integration for automated repository creation and file commits.
Non-blocking: gracefully degrades if GITHUB_TOKEN is not configured.
"""

import logging
from pathlib import Path
from config.settings import settings
from modules.common.logger import platform_logger
logger = platform_logger


def create_repo_and_push(app_name: str, project_dir: Path, description: str = "") -> str | None:
    """
    Create a GitHub repository and push all generated project files.

    Args:
        app_name: Repository name (will be slugified).
        project_dir: Local directory containing all generated files.
        description: Repository description.

    Returns:
        The repository HTML URL if successful, None if GitHub is not configured.
    """
    if not settings.github_enabled:
        logger.info(
            "[GitHubTool] GITHUB_TOKEN not configured — skipping repository creation. "
            "Add GITHUB_TOKEN to .env to enable this feature."
        )
        return None

    try:
        from github import Github, GithubException
    except ImportError:
        logger.warning("[GitHubTool] PyGithub not installed — skipping repository creation.")
        return None

    try:
        g = Github(settings.github_token)
        user = g.get_user()
        org = settings.github_org

        # Create repository
        owner = g.get_organization(org) if org else user
        try:
            repo = owner.create_repo(
                name=app_name,
                description=description or f"Generated by E-to-E Agent",
                private=(settings.github_default_visibility == "private"),
                auto_init=False,
            )
            logger.git(f"Created repo: {repo.html_url}", repo=repo.html_url)
        except GithubException as e:
            if e.status == 422:  # Already exists
                repo = owner.get_repo(app_name)
                logger.warning(f"Repo already exists: {repo.html_url}")
            else:
                raise

        # Commit files in logical groups
        _push_directory(repo, project_dir, "database", "feat: add database models and migrations")
        _push_directory(repo, project_dir, "backend",  "feat: add FastAPI backend")
        _push_directory(repo, project_dir, "frontend", "feat: add React frontend")
        _push_directory(repo, project_dir, "infra",    "chore: add Docker and CI/CD configuration")
        _push_directory(repo, project_dir, "docs",     "docs: add project documentation")
        _push_root_files(repo, project_dir)

        logger.git(f"All files pushed to {repo.html_url}", repo=repo.html_url)
        return repo.html_url

    except Exception as exc:
        logger.error(f"Repository creation failed: {exc}")
        return None


def _push_directory(repo, project_dir: Path, component: str, commit_message: str) -> None:
    """Commit all files in a component sub-directory."""
    from github import InputGitTreeElement

    component_dir = project_dir / component
    if not component_dir.exists():
        return

    files_to_commit = []
    for file_path in component_dir.rglob("*"):
        if file_path.is_file() and ".venv" not in str(file_path):
            rel_path = file_path.relative_to(project_dir)
            try:
                content = file_path.read_text(encoding="utf-8")
                files_to_commit.append((str(rel_path), content))
            except (UnicodeDecodeError, PermissionError):
                pass  # Skip binary or unreadable files

    if not files_to_commit:
        return

    _batch_commit(repo, files_to_commit, commit_message)


def _push_root_files(repo, project_dir: Path) -> None:
    """Commit README.md and other root-level files."""
    root_files = list(project_dir.glob("*.md")) + list(project_dir.glob("*.yml"))
    files_to_commit = []
    for fp in root_files:
        if fp.is_file():
            try:
                files_to_commit.append((fp.name, fp.read_text(encoding="utf-8")))
            except (UnicodeDecodeError, PermissionError):
                pass
    if files_to_commit:
        _batch_commit(repo, files_to_commit, "docs: add root project files")


def _batch_commit(repo, files: list[tuple[str, str]], commit_message: str) -> None:
    """Create a tree-based commit for multiple files at once."""
    from github import InputGitTreeElement
    try:
        master_ref = repo.get_git_ref("heads/main")
        master_sha = master_ref.object.sha
        base_tree = repo.get_git_tree(master_sha)

        tree_elements = [
            InputGitTreeElement(path=path, mode="100644", type="blob", content=content)
            for path, content in files
        ]
        new_tree = repo.create_git_tree(tree_elements, base_tree)
        parent = repo.get_git_commit(master_sha)
        new_commit = repo.create_git_commit(commit_message, new_tree, [parent])
        master_ref.edit(new_commit.sha)
    except Exception as exc:
        # Try initializing with first commit
        try:
            repo.create_file(files[0][0], commit_message, files[0][1])
            for path, content in files[1:]:
                try:
                    repo.create_file(path, commit_message, content)
                except Exception:
                    pass
        except Exception as inner_exc:
            logger.warning(f"[GitHubTool] Batch commit failed: {inner_exc}")
